name: ci

on:
  pull_request:
    branches: 
      - homolog
jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v4.1.1
      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Checkout submodules
        run: git submodule update --init --recursive
               
      - name: Criação da Imagem docker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            secultceara/mapasculturais:5.8.15
            secultceara/mapasculturais:latest
