name: CICD_PROD

on:
  pull_request:
    branches: 
      - main
    types:
      - closed
  
  workflow_dispatch:

jobs:
  BUILD:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps: 
      
      - uses: actions/checkout@v4.1.1

      - name: Read version file
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "app_version=$VERSION" >> $GITHUB_ENV
      
      - name: Docker Login  
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Checkout submodules
        run: git submodule update --init --recursive
               
      - name: Criação da Imagem docker
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            secultceara/mapasculturais:latest
            secultceara/mapasculturais:${{ env.app_version }}

